project: templatecv

use_wandb: False

dataset:
  name: CustomDataset
  path: ./data/inaturalist_12K/
  img_size: 256
  class_names: ['Plantae', 'Mammalia', 'Animalia', 'Reptilia', 'Amphibia', 'Aves', 'Fungi', 'Arachnida', 'Mollusca', 'Insecta']
  batch_size: 5

train:
  epochs: 1
  val_interval: 1